spring.application.name=EatTakeOut

# 视图解析器配置
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# 服务器配置
server.port=8080

# 数据库配置
spring.datasource.url=jdbc:mysql://freemysql-freedb.g.aivencloud.com:22506/seatidedb?useSSL=false&serverTimezone=UTC
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
#数据库用户名和密码填下面

# JPA配置
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# 执行SQL脚本
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql